services:
  haskell:
    build:
      context: .
      dockerfile: docker/Dockerfile-haskell
    container_name: haskell
    network_mode: none
    volumes:
      - ./docker/prettify.hs:/home/bot/prettify.hs:ro
  node:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: pdep-bot
    depends_on:
      - haskell
    env_file: .env
    image: pdep-bot:v1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

version: '3.9'
